steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_REGION-docker.pkg.dev/$PROJECT_ID/silvia-repo/silvia-frontend:latest', '-f', 'frontend/Dockerfile', '.']
images:
- '$_REGION-docker.pkg.dev/$PROJECT_ID/silvia-repo/silvia-frontend:latest'
